Args=--enable-native-access=ALL-UNNAMED --future-defaults=all --initialize-at-build-time=sun.nio.cs
#-H:+AddAllCharsets
#-march=compatibility
#--exact-reachability-metadata #Diagnose Missing Metadata Registration
#--static-nolibc
