Args=--enable-native-access=ALL-UNNAMED --future-defaults=all
#--exact-reachability-metadata #Diagnose Missing Metadata Registration
#--initialize-at-build-time=sun.nio.cs #did not work
#--static-nolibc
#-H:+AddAllCharsets #+6 MiB
#-march=compatibility
