writer0=main
writer0.charset=UTF-8
writer0.format={date: ss:SSS} {message}
writer0.level=info
writer1=console
writer1.charset=UTF-8
writer1.format={date: ss:SSS}-{level-code} {message}
writer1.level=info
writer2=rolling file
writer2.append=false
writer2.backups=100
writer2.buffered=true
writer2.charset=UTF-8
writer2.file=#{java.io.tmpdir}/euaie/{date}.log
writer2.format={date: mm:ss:SSS}-{level-code} {message}
writer2.level=debug
writer3=file
writer3.append=true
writer3.buffered=false
writer3.charset=UTF-8
writer3.file=#{java.io.tmpdir}/euaie/error.log
writer3.format={date} {message}
writer3.level=error
