writer0=main
writer0.charset=UTF-8
writer0.format={date: mm:ss:SSS} {message}
writer0.level=info
writer1=console
writer1.charset=UTF-8
writer1.format={date: mm:ss:SSS}#{level-code} {message}
writer1.level=debug
writer2=rolling file
writer2.append=false
writer2.backups=10
writer2.buffered=true
writer2.charset=UTF-8
writer2.file=#{java.io.tmpdir}/euaie/{date}.log
writer2.format={date: mm:ss:SSS}#{level-code} {message}
writer2.level=debug
