name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: graalvm
          java-version: 25
      - run: ./gradlew -v
      - run: ./gradlew shadowJar
      - run: ./gradlew nativeCompile
      - run: ls -lh _tui/build/jar/ _tui/build/native/nativeCompile/
      - run: upx _tui/build/native/nativeCompile/*
      - run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --draft \
            _tui/build/jar/* \
            _tui/build/native/nativeCompile/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
