name: Test
on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: ls -al
      - run: cd _tui
      - run: ls -al
      - run: find --version
